Replace Appveyor by GitHub Actions for Windows
zulip/zulip-desktop pull request #1350
Opened 2024-01-10 15:44 UTC by yaminijha1

---

**What's this PR do?**
 Fixes #1070  

This PR remove the Appveyor CI workflow and adds GitHub Actions on Windows build

2025-06-18 13:09 UTC, shubham-padia requested changes
Sorry for the delay. Overall looks good, requested some changes. @yaminijha1 let me know if you will be interested to make those changes or not. If not, I can make those changes and add you as a co-author.

2025-06-18 13:09 UTC, shubham-padia commented on .github/workflows/node.js.yml
> +          node-version: "17"
Can you change this to `lts/*`, so we get the latest node version.

2025-06-18 13:09 UTC, shubham-padia commented on .github/workflows/node.js.yml
> +        uses: actions/setup-node@v3
We should use setup-node@v4 since that's the latest version

2025-06-19 05:30 UTC, shubham-padia commented
@yaminijha1 Can you squash the second commit into the first? Thanks!

2025-06-20 03:20 UTC, yaminijha1 commented
Hi ~shubham-padia,
This PR #1350 now fixes #1070 and incorporates all your suggestions:

Updated the Node.js version to lts/*
Switched to setup-node@v4
Squashed the commits into one, as requested

Please let me know if any further changes are needed.

2025-06-20 07:49 UTC, shubham-padia commented
@timabbott this should be ready for integration review

2025-08-07 17:57 UTC, yaminijha1 commented
@zulipbot @timabbott  this PR #1350  now fixes #1070 without any conflict without any conflict.

2025-11-16 07:28 UTC, andersk commented
- If we’re running more or less the same steps on both platforms, this should use a [matrix](https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations).

- The extra `node --version` and `npm --version` are not needed because GitHub already includes these in the log under **Run actions/setup-node@v4** → **Environment details**. `python --version` is not needed because we do not use Python.

- The Appveyor badge needs to be removed from `README.md`.

2025-11-20 00:24 UTC, closed without merging