Settings: improved visibility of text and buttons
zulip/zulip-desktop pull request #1367
Opened 2024-04-23 10:43 UTC by Aitchessbee

**What's this PR do?**
Improves text and button visibility in settings page as reported in #1357 

**Screenshots?**
![image](https://github.com/zulip/zulip-desktop/assets/45175270/a0520cc0-beda-4f5a-b693-e797bd0cfbbc)

**You have tested this PR on:**

- [ ] Windows
- [ ] Linux/Ubuntu
- [ ] macOS

2024-04-24 01:02 UTC, timabbott commented
Can you present before/after screenshots? Also, I'm not sure which component is the `settings_description` part.

2024-04-24 09:28 UTC, Aitchessbee commented
Update the description with old and new images... `settings_description` is a class given to the text in each row. It was already present in the code but wasn't used in css.

2024-04-25 00:25 UTC, timabbott commented
OK. Text definitely feels a lot better. The dark grey slider background might be overdoing it a bit; is there somewhere a bit in between worth trying?

2024-04-30 22:42 UTC, alya commented
Maybe, but overall this is a definite improvement.

2024-07-09 08:42 UTC, Axshatt commented
> OK. Text definitely feels a lot better. The dark grey slider background might be overdoing it a bit; is there somewhere a bit in between worth trying?

I think the tab headings should also be in dark colour as it will be a good user experience

2025-10-24 09:33 UTC, shubham-padia requested changes
Thanks for your PR! Please rebase your PR. Requested 1 change, rest looks good.

2025-10-24 12:17 UTC, shubham-padia commented on app/renderer/css/preference.css
> +
We don't need this anymore, because of https://github.com/zulip/zulip-desktop/commit/b42f9de27d92c358bc4f0979d892d34a27be053d

2025-11-10 04:05 UTC, shubham-padia commented
Opened #1468 with the requested change and commit message fixes while keeping the original author same.

2025-11-25 22:27 UTC, timabbott commented
Closing in favor of #1468.

2025-11-25 22:27 UTC, closed without merging