Set user-agent from a singleton util.
zulip/zulip-desktop pull request #174
Opened 2017-06-11 17:08 UTC by geeeeeeeeek

#172

2017-06-11 18:17 UTC, akashnimare requested changes
Also - https://travis-ci.org/zulip/zulip-electron/jobs/241772249#L293

2017-06-11 18:17 UTC, akashnimare commented on app/renderer/js/utils/system-util.js
> +		this.userAgent = 'ZulipElectron/' + webViewUserAgent;
Prettify -
```javascript
		this.userAgent = 'ZulipElectron' + ' ' + webViewUserAgent;

2017-06-12 03:33 UTC, geeeeeeeeek commented
`"ZulipElectron/0.5.10 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Zulip/0.5.10 Chrome/56.0.2924.87 Electron/1.6.8 Safari/537.36"`

@akashnimare Added the mission app version. Cross-check please 😄

2017-06-12 09:27 UTC, akashnimare commented
LGTM. Merged. Thanks, @geeeeeeeeek.

2017-06-12 09:27 UTC, merged