Badge update branch
zulip/zulip-desktop pull request #227
Opened 2017-07-20 17:27 UTC by fragm3

Added enhancement, deck unread message toggle feature added to the setting page.
macOS Sierra Version: 10.12.5.
Issue: #192 
Type: Enhancement

<img width="650" alt="off" src="https://user-images.githubusercontent.com/18073126/28430568-9b772c08-6d9e-11e7-96ca-884821fa3bcd.png">

<img width="650" alt="on" src="https://user-images.githubusercontent.com/18073126/28430578-a4fed6f4-6d9e-11e7-8d65-c773a0773194.png">

2017-07-22 19:53 UTC, akashnimare requested changes

2017-07-22 19:53 UTC, akashnimare commented on app/renderer/js/pages/preference/general-section.js
> +			ipcRenderer.send('toggle-dock-unread', newValue);
It should not be here.

2017-07-25 10:30 UTC, akashnimare commented
This needs a rebase and I'll review!

2017-08-02 15:38 UTC, fragm3 reviewed
Dock unread feature settings

2017-08-26 23:44 UTC, akashnimare commented
Added in https://github.com/zulip/zulip-electron/commit/21f01d268a53edea2c4e0e5ba3aecb5bb63f1133.

2017-08-26 23:44 UTC, closed without merging