about-page: add links for zulip-electron and license
zulip/zulip-desktop pull request #346
Opened 2017-12-02 19:03 UTC by cPhost

2017-12-02 19:22 UTC, akashnimare requested changes

2017-12-02 19:22 UTC, akashnimare commented on app/renderer/css/about.css
>  }
Can you add a `cursor: pointer` property here?

2017-12-02 19:22 UTC, akashnimare commented on app/renderer/about.html
> +				Maintained by <a onclick="linkInBrowser('repo')">Zulip</a>
The URL for Zulip should be https://zulipchat.com, right @rishig ?

2017-12-02 19:47 UTC, cPhost commented
@akashnimare or @rishig can you add GCI Task for this two PR Please, Thanks.

2017-12-03 19:02 UTC, rishig commented
Thanks for looking into this @cPhost! This already looks much better. 
Before merging: could you post a screenshot of the corresponding pages for slack and nylas?

2017-12-03 19:16 UTC, akashnimare approved these changes

2017-12-03 19:23 UTC, akashnimare commented
Slack -

![image](https://user-images.githubusercontent.com/2263909/33528822-641bbf08-d88d-11e7-855b-635e787393d7.png)

2017-12-03 19:31 UTC, rishig commented
ok, great. 
Also, I'm not sure this is the most natural place for the "Report an issue" button, but that can be dealt with separately.

2017-12-03 21:36 UTC, akashnimare commented
I have put it intentionally there so that users can find it and file the bug. Let's keep it as it is for now. We have the "Report an issue" in `Help` menu item -
 
![image](https://user-images.githubusercontent.com/2263909/33530078-ec451f02-d89f-11e7-9d3a-068806dd1ea7.png)

2017-12-03 23:03 UTC, cPhost commented
Just fixed it so it has Apache 2.0 license.

2017-12-04 09:24 UTC, merged

2017-12-04 09:24 UTC, akashnimare commented
Merged, thanks @cPhost 🚀