gitlint: Setup commit linter.
zulip/zulip-desktop pull request #367
Opened 2017-12-28 19:44 UTC by cPhost

This will setup a commit hook that will check the commit msg run
`npm run lint-commits` to check all the commits.

---

**What's this PR do?**
Setup commit linter.

**Screenshots?**
![screen shot 2017-12-28 at 2 18 09 pm](https://user-images.githubusercontent.com/23620441/34421497-9dfe9e9e-ebdd-11e7-98a9-24dd8c01f056.png)
![screen shot 2017-12-28 at 2 10 17 pm](https://user-images.githubusercontent.com/23620441/34421498-9e11d90a-ebdd-11e7-845a-da1359e0b1c6.png)

**You have tested this PR on:**
  - [ ] Windows
  - [X] Linux/Ubuntu
  - [X] macOS

2018-01-05 17:54 UTC, akashnimare requested changes

2018-01-05 17:54 UTC, akashnimare commented on scripts/gitlint/setup-gitlint-hook.js
> +// git hook which we will be used to lint
`which we will` = `which will`

2018-01-05 18:01 UTC, akashnimare requested changes

2018-01-05 18:01 UTC, akashnimare commented on package.json
> +    "lint-fix": "xo --fix",
Can you remove `lint-fix` because `xo --fix` doesn't work all the time and may give you unexpected results.

2018-01-29 18:26 UTC, akashnimare approved these changes

2019-07-03 15:21 UTC, priyank-p commented
This thing is almost three years old :). Closing this I don't think we want this now.

2019-07-03 15:23 UTC, akashnimare commented
@kanishk98 and I were thinking to revisit this. We definitely want to add this tool.

2019-07-03 15:25 UTC, priyank-p commented
OK, restored I don't remember anything at this point so closed it, reopening.

2026-06-05 00:04 UTC, closed without merging