tray-icon: Include unread count in tray icon.
zulip/zulip-desktop pull request #382
Opened 2018-01-14 01:19 UTC by cPhost

**What's this PR do?**
This PR adds unread counts to tray icon, like zulip favicons

2018-01-14 08:53 UTC, akashnimare commented
Not visible on W10 -

![image](https://user-images.githubusercontent.com/2263909/34914322-6301418c-f936-11e7-97de-11c503f4835b.png)

2018-01-14 18:02 UTC, akashnimare requested changes

2018-01-14 18:02 UTC, akashnimare commented on app/renderer/js/tray.js
> +		image.src = '../resources/icon.png';
should be `Icon.png`.

2018-01-15 18:29 UTC, cPhost commented
Closing this since this is fixed in tray-icon branch.

2018-01-15 18:29 UTC, closed without merging