windows: Add tools support with batch scripts.
zulip/zulip-desktop pull request #403
Opened 2018-02-01 01:52 UTC by cPhost

Add windows support.

2018-02-01 17:44 UTC, akashnimare requested changes

2018-02-01 17:44 UTC, akashnimare commented on tools/reinstall-node-modules.cmd
> +deltree /y node_modules
This doesn't work. Use `rmdir /s /q`.

2018-02-01 17:54 UTC, cPhost commented on tools/reinstall-node-modules.cmd
> +deltree /y node_modules
I fixed it. BTW do other script works?

2018-02-01 18:04 UTC, akashnimare approved these changes

2018-02-01 23:16 UTC, cPhost commented
Here is how to use this in windows:
Regular old cmd prompt: `.\tools\fetch-pull-request` no need to have .cmd at the end.
Git Bash and powershell: `./tools/fetch-pull-request` just like unix

2018-02-02 22:38 UTC, akashnimare commented on tools/reinstall-node-modules.cmd
>  rmdir /s /q node_modules
@cPhost somewhere here.

2018-02-02 22:43 UTC, akashnimare commented on tools/reinstall-node-modules.cmd
> +echo "node_modules removed reinstlling npm packages"
Typo - **reinstalling**

2018-02-02 22:44 UTC, akashnimare requested changes

2018-02-02 22:44 UTC, akashnimare commented on tools/reinstall-node-modules
> +echo "node_modules removed reinstlling npm packages"
Typo - **reinstalling**

2018-02-02 22:45 UTC, akashnimare approved these changes

2018-02-09 12:49 UTC, merged

2018-02-09 12:49 UTC, akashnimare commented
Merged, thanks @cPhost 🚀