[WIP] Only show the back button if it needed.
zulip/zulip-desktop pull request #426
Opened 2018-02-21 20:09 UTC by abhigyank

Need review.

Everything works well, except a small issue described [here](https://chat.zulip.org/#narrow/stream/16-electron/topic/zulip-electron.20.2F.20master).

Address [issue 421](https://github.com/zulip/zulip-electron/issues/421)

**What's this PR do?**

**Any background context you want to provide?**

**Screenshots?**

**You have tested this PR on:**
  - [ ] Windows
  - [ ] Linux/Ubuntu
  - [ ] macOS

2018-02-21 20:10 UTC, abhigyank commented
@zulipbot label "needs review"

2018-02-21 21:47 UTC, cPhost commented
@abhigyank you need to used [`did-navigate-in-page`](https://electronjs.org/docs/api/webview-tag#event-did-navigate-in-page) event of web-view to track of the state, to know weather its time to update the button or not checking it on first time does work.

2018-02-22 14:56 UTC, akashnimare requested changes

2018-02-22 14:56 UTC, akashnimare commented on app/renderer/js/components/webview.js
> +			if (event.url.includes('renderer/preference.html')) {
We could use it like - 
```
const isSettingPage = event.url.includes('renderer/preference.html');
if (isSettingPage) {
   return;
}
```

2018-02-22 18:59 UTC, akashnimare approved these changes

2018-02-22 19:23 UTC, merged

2018-02-22 19:23 UTC, akashnimare commented
Merged. Thanks, @abhigyank.