electron-bridge: Implement electron bridge.
zulip/zulip-desktop pull request #428
Opened 2018-02-25 20:28 UTC by cPhost

2018-02-26 00:39 UTC, cPhost commented
Side-effect of force-pushing, reopening..

2018-06-04 21:09 UTC, akashnimare requested changes

2018-06-04 21:09 UTC, akashnimare commented on app/main/index.js
> +		mainWindow.webContents.send('update-realm-icon', serverURL, iconURL);
`mainWindow.webContents` should be `page`.

2018-06-04 21:09 UTC, akashnimare commented on app/renderer/js/electron-bridge.js
> +// for the wole file.
Typo - *whole

2018-06-04 21:11 UTC, akashnimare commented
This looks good. Can you fix above minor changes and resolve conflicts?

2018-06-04 21:38 UTC, priyankp10 commented
Fixed, and rebased.

2018-06-05 19:59 UTC, akashnimare commented
@priyankp10 I'm getting following errors -

![image](https://user-images.githubusercontent.com/2263909/40999524-c919c5e0-6928-11e8-9c6d-a8ff0acd1b2b.png)

This doesn't let me update the icon for the first time only, later I can see the changes.

Reproduce -
* Run Zulip server
* Start Zulip app
* Add http://localhost:9991
* Try to update the realm icon

2018-06-05 20:19 UTC, akashnimare commented
I think the bug lies in the index of the tab -
```js
const serverImgSelector = `.tab[data-tab-id="${index}"] .server-icons`;`
```
The `data-tab-id` will keep changing as you navigate in the app. Maybe get the server tab using the active class?

2018-06-05 20:35 UTC, priyankp10 commented
Yeah, using `.active` is the right solution here. Although the `data-user-id` changing is a bug we would need to fix right?

2018-07-13 16:54 UTC, abhigyank commented
@priyankp10  Hey, Akash and me met at the Zulip retreat so we decided to complete the work on this PR so that we can make use of the `electron_bridge` feature. Thanks for implementing this! :rocket:

2018-07-13 16:55 UTC, priyankp10 commented
Done in #516.

2018-07-13 16:55 UTC, closed without merging