il8n: Add locale helper script.
zulip/zulip-desktop pull request #437
Opened 2018-03-04 02:58 UTC by cPhost

This script automatically builds locales if the template is changed. it sorts the outputted JSON.

2018-03-04 05:21 UTC, akashnimare requested changes

2018-03-04 05:21 UTC, akashnimare commented on tools/locale-helper/index.js
> +            const translatedText = res.text.split('\n').sort();
@cPhost we don't need to sort this.

2018-03-04 05:21 UTC, akashnimare commented on tools/locale-helper/index.js
> +const supportedLangs = translate.languages;
this is what we need to use here (we only support following languages)- 
```javascript
const supportedLangs = {
    "de": "Deutsch",
    "pl": "polski",
    "en": "English",
    "cs": "česky",
    "hi": "Hindi",
    "ru": "Русский",
    "co-id": "Indonesia",
    "bg": "български",
    "hu": "Magyar",
    "sr": "српски",
    "ml": "Malayalam",
    "ta": "தமிழ்",
    "nl": "Nederlands",
    "ja": "日本語",
    "pt": "Português",
    "codeans": "简体中文",
    "tr": "Türkçe",
    "codeant": "繁體中文",
    "es": "español",
    "ko": "한국어",
    "fr": "français"
};
```
put it in `support-lang.js` and export.

2018-03-04 05:24 UTC, akashnimare requested changes

2018-03-04 05:24 UTC, akashnimare commented on app/translations/template.json
> +{
We should short this file and put it in `/locale-helper/template.json`.

2018-03-04 15:22 UTC, priyank-p commented on app/translations/en.json
> +	"About Zulip": "About Zulip",
After i saw this i intentionally left this here, it would be helpful to check if something is wrong with writing translation files :).

2018-03-04 15:23 UTC, cPhost commented on app/translations/en.json
> +	"About Zulip": "About Zulip",
Specially with all this sorting stuff. I doubt it would be hard to catch if something is wrong with a wired diff but still.

2018-03-04 15:25 UTC, cPhost commented
Every single translation is done except the `codeans` and `codeant` one. I might be worth looking up there local and add it, i will handle this once i have time for it.

2018-03-05 23:16 UTC, akashnimare approved these changes

2018-03-05 23:31 UTC, akashnimare commented
Looks like that module doesn't support `zh-Hans` and `zh-Hant`. We gotta add them manually.

2018-03-05 23:38 UTC, merged

2018-03-05 23:39 UTC, akashnimare commented
Merged. Thanks, @cPhost. @ihsavru you might want to rebase and clean up #436.