realm name: Update sidebar realm name when it's changed in webapp.
zulip/zulip-desktop pull request #553
Opened 2018-09-02 06:50 UTC by abhigyank

This PR updates the realm name in the sidebar tooltip and domains.json when it is updated in the server through electron_bridge.

This PR  also removes the server.alias parameter from the tooltip `onHover` function and inserts it in the the innerHTML of the tooltip DOM, This helps to easily update the tooltip text when the realm name is changed. Since this text is never removed this is a good way to do this as we now simply leverage `display:none` to hide/show the tooltip.

Fixes: #425

2018-09-03 06:21 UTC, akashnimare requested changes

2018-09-03 06:21 UTC, akashnimare commented on app/renderer/js/ans,txt
> +1. 127.0.0.1 0.047 ms
@abhigyank what's the purpose of this file?

2018-09-03 06:22 UTC, abhigyank commented on app/renderer/js/ans,txt
> +1. 127.0.0.1 0.047 ms
This is some other file that came into the repository folder by mistake I guess. My bad.
Will remove and push.

2018-09-03 06:34 UTC, akashnimare approved these changes

2018-09-08 11:15 UTC, akashnimare commented on app/renderer/js/main.js
> +					this.tabs[index].props.name = escape(realmName);
Do we really need to escape this and the `webview.props.name` ?

2018-09-08 11:19 UTC, abhigyank commented on app/renderer/js/main.js
> +					this.tabs[index].props.name = escape(realmName);
This was to maintain uniformity and be on the safe side in case.

2018-09-08 13:21 UTC, abhigyank commented on app/renderer/js/main.js
> +					this.tabs[index].props.name = escape(realmName);
I think we should remove it for the `webview.props.name` since it is being used by the Windows Menu.

2018-09-11 15:33 UTC, merged

2018-09-11 15:33 UTC, akashnimare commented
Thanks, @abhigyank.

2018-09-27 22:16 UTC, timabbott commented
Is there a zulip/zulip commit related to this that we need to merge as well?

2018-09-28 04:21 UTC, abhigyank commented
No, the required part in zulip/zulip was merged earlier.